### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RDKRACZ** [OverlordsIII/VillagerNames#11]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 21.12.20 21:28
Description: Ticking memory connection

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at io.github.overlordsiii.villagernames.util.VillagerUtil.updateWanderingTraderNames(VillagerUtil.java:195)
	at io.github.overlordsiii.villagernames.VillagerNames.lambda$onInitialize$1(VillagerNames.java:50)
	at net.minecraft.class_3218.handler$zjb000$onLoadEntity(class_3218.java:3580)
	at net.minecraft.class_3218.method_18778(class_3218.java:938)
	at net.minecraft.class_3218.method_18214(class_3218.java:846)
	at net.minecraft.class_3898.method_17227(class_3898.java:635)
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at net.minecraft.class_3898.method_20460(class_3898.java:611)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1269)
	at net.minecraft.class_3215.method_12121(class_3215.java:1165)
	at net.minecraft.class_1937.method_8402(class_1937.java:209)
	at net.minecraft.class_3218.method_18771(class_3218.java:815)
	at net.minecraft.class_3218.method_18213(class_3218.java:798)
	at net.minecraft.class_3324.method_14570(class_3324.java:224)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$baa000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_275, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Amazon.com Inc.
	Memory: 2717322736 bytes (2591 MB) / 3305111552 bytes (3152 MB) up to 4060086272 bytes (3872 MB)
	CPUs: 4
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3867m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		atbyw: All The Blocks You Want (ATBYW) 1.2.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		charm: Charm 2.1.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cullleaves: Cull Leaves 1.0.0
		fabric: Fabric API 0.28.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.2+a03e98793a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fiber: fiber 0.23.0-2
		hydrogen: Hydrogen 0.1.1
		ironfurnaces: Iron Furnaces 2.2.1
		jumplessstep: Jumpless Step 0.1.0+1.16.1
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.14.13+build.19
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		phosphor: Phosphor 0.7.0+build.10
		polymorph: Polymorph 0.0.6-1.16.4
		sodium: Sodium 0.1.0
		unlittorches: Unlit Torches 2.0.0
		villagernames: Villager Names 1.5.2
		xhp: xhp 1.0.0
	Player Count: 1 / 8; [class_3222['_K0RR_'/110, l='ServerLevel[New World]', x=1815.91, y=59.00, z=-5328.30]]
	Data Packs: vanilla, file/all-the-stone-tools+mo'-sticks+stone-surprise datapack.zip, fabric/atbyw, fabric/fabric-tool-attribute-api-v1, fabric/charm (incompatible), fabric/unlittorches, file/Devons TRUE SURVIVAL Version 2.3.3.zip, file/Mob_Statues_Vanilla_1.2.zip (incompatible), file/No_More_Zoombies_1.1.zip (incompatible), file/Prospecting Ver 0.1 - Devons TRUE SURVIVAL.zip, file/StoneLoot+V6.zip (incompatible), file/UHC_module_CutClean_1.1.zip (incompatible), file/autosmelty.zip, file/extra-stone-drops-1-0-0.zip (incompatible), fabric/ironfurnaces, fabric/fabric-furnaces
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by OverlordsIII** [comment]
I have uploaded a fix on curseforge, try to get the latest release and see if it works out.
