### ISSUE TITLE
[Bug] Compatibility Villager Names - Carpet 1.19.2

### ISSUE THREAD

**Issue by SylisMC** [OverlordsIII/VillagerNames#52]
**Minecraft 1.19.2**

Crash on boot (no main menu) **1.19.2**

fabric-carpet-1.19.2-1.4.84+v221018.jar
villagernames-1.19.2-4.0.8.jar

[Villager Names Github Issue](https://github.com/OverlordsIII/VillagerNames/issues/52)
[Carpet Githup Issue](https://github.com/gnembon/fabric-carpet/issues/1618)

[2023-01-01-1.log.gz](https://github.com/gnembon/fabric-carpet/files/10329917/2023-01-01-1.log.gz)

**Comment by OverlordsIII** [comment]
This was fixed recently. Please update to the latest version of the mod (4.4.0), found [here](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/4271251)

**Comment by OverlordsIII** [comment]
[Here's](https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/4362002) a 1.19.2 version.

**Comment by jiriks74** [comment]
Cannot confirm that it's working with 4.5.0:

<details>
<summary>Error from console</summary>

```java
[00:17:21] [main/INFO]: Mixing server.MixinPlayer from nochatreports.mixins.json into net.minecraft.class_1657
[00:17:21] [main/WARN]: @Redirect conflict. Skipping villagernames.mixins.json:LivingEntityMixin from mod villagernames->@Redirect::turnOfConsole(Lnet/minecraft/class_1309;)Z with priority 1000, already redirected by carpet.mixins.json:LivingEntity_cleanLogsMixin from mod carpet->@Redirect::shouldLogDeaths(Lnet/minecraft/class_1309;)Z with priority 1000
[00:17:21] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1309 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_6396.handler
```

</details>

**Comment by OverlordsIII** [comment]
Try with this new version (4.5.1): https://www.curseforge.com/minecraft/mc-mods/villager-names-fabric/files/4426546

**Comment by jiriks74** [comment]
Starts up for me! Villagers look or and Carpet with EssentialAddons seem to be working!

**Comment by OverlordsIII** [comment]
Great! Thanks for reporting.
