### ISSUE TITLE
Crash on villagers mating

### ISSUE THREAD

**Issue by Riimu** [OverlordsIII/VillagerNames#9]
Updated to the latest version (was using 1.3.0 previously) and now the game seems to be crashing whenever two villagers are making a child.

Based on the stack trace, I'd venture a guess it has something to do with the changes related to adding support for last names in: https://github.com/OverlordsIII/VillagerNames/blob/b23cd700583855b1b13a66d7ed0e87d8a0dcca75/src/main/java/io/github/overlordsiii/villagernames/mixin/VillagerBreedTaskMixin.java#L21-L25

Stack trace from a crash:

```
Time: 12/11/20 7:53 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at java.util.Objects.requireNonNull(Objects.java:203)
	at net.minecraft.class_4111.handler$znj000$onCreateChild(class_4111.java:524)
	at net.minecraft.class_4111.method_18970(class_4111.java:149)
	at net.minecraft.class_4111.method_20643(class_4111.java:94)
	at net.minecraft.class_4111.method_18975(class_4111.java:79)
	at net.minecraft.class_4111.method_18924(class_4111.java:25)
	at net.minecraft.class_4097.method_18923(class_4097.java:63)
	at net.minecraft.class_4103.method_18932(class_4103.java:61)
	at net.minecraft.class_4103$$Lambda$6586/1740185597.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_4103.method_18924(class_4103.java:61)
	at net.minecraft.class_4097.method_18923(class_4097.java:63)
	at net.minecraft.class_4095.method_19545(class_4095.java:521)
	at net.minecraft.class_4095.method_19542(class_4095.java:466)
	at net.minecraft.class_1646.method_5958(class_1646.java:272)
	at net.minecraft.class_1308.method_6023(class_1308.java:982)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:682)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:430)
	at net.minecraft.class_1646.method_5773(class_1646.java:313)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_3218$$Lambda$6546/1023197450.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:118)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$6212/72944275.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by OverlordsIII** [comment]
What okay, didn't know github autocloses stuff like that

**Comment by OverlordsIII** [comment]
Just uploaded a potential fix for this on curseforge, try to get the latest release
